prevent grep from returning 1 on no-match

diff --git a/frontend/s/fmt b/frontend/s/fmt
--- a/frontend/s/fmt
+++ b/frontend/s/fmt
@@ -10,9 +10,18 @@ if [[ -f ../.env ]]; then
     set +a
 fi
 
+# ensure grep doesn't return exit code 1 on no match
+c1grep() {
+  grep "$@" || test $? = 1
+}
+
 GLOB="\.(js|jsx|scss|css|ts|tsx|json)$"
 
 FILES=$(git diff --name-only master | sed -e "s%frontend/%%"| grep -E "$GLOB")
+
+if [[ -n "$FILES" ]]; then
+  exit 0
+fi
 
 ARGS="$@"
 if [[ $ARGS == *'--list-different'* ]]; then
diff --git a/frontend/s/lint b/frontend/s/lint
--- a/frontend/s/lint
+++ b/frontend/s/lint
@@ -10,11 +10,20 @@ if [[ -f ../.env ]]; then
     set +a
 fi
 
+# ensure grep doesn't return exit code 1 on no match
+c1grep() {
+  grep "$@" || test $? = 1
+}
+
 node scripts/lint.js
 
 GLOB="^src.*\.(ts|tsx)$"
 
-FILES=$(git diff --name-only master | sed -e "s%frontend/%%"| grep -E "$GLOB")
+FILES=$(git diff --name-only master | sed -e "s%frontend/%%"| c1grep -E "$GLOB")
+
+if [[ -n "$FILES" ]]; then
+  exit 0
+fi
 
 $(yarn bin)/tslint --project ./tsconfig.json --format 'codeFrame' $FILES
 
